"""Provider-neutral domain contracts for the v3 pipeline.

This package must stay importable with only the Python standard library.  It is
deliberately not wired into the MVP-0 runtime until the v3 safety gates exist.
"""

from snapquiz.domain.capture import (
    CaptureArtifact,
    CaptureConstraints,
    CaptureRect,
    CaptureScope,
    CaptureScopeKind,
    CoordinateSpace,
    validate_capture_artifact,
)
from snapquiz.domain.adapter import (
    ANSWER_CANDIDATE_SCHEMA_VERSION,
    MAX_PROVIDER_RESPONSE_BYTES,
    TRANSPORT_RESPONSE_SCHEMA_VERSION,
    AnswerCandidateResult,
    NormalizedRefusal,
    TransportResponse,
)
from snapquiz.domain.capabilities import (
    CapabilityRole,
    CredentialBindingMetadata,
    CredentialValueScheme,
    EndpointOperationTemplate,
    EndpointPolicySnapshot,
    ImageInputKind,
    InputModality,
    ModelCapabilitiesSnapshot,
    PipelineProfileSnapshot,
    ProviderApplicationState,
    ProviderProfileSnapshot,
    RedirectPolicy,
    StageBindingSnapshot,
    StructuredOutputKind,
)
from snapquiz.domain.digest import (
    CANONICAL_SERIALIZER_VERSION,
    Digest256,
    canonical_json_bytes,
    digest256,
)
from snapquiz.domain.intent import (
    MAX_USER_HINT_CHARS,
    SOLVE_INTENT_DIGEST_SCHEMA_VERSION,
    SOLVE_INTENT_SCHEMA_VERSION,
    OutputTokenLimit,
    SolveIntent,
)
from snapquiz.domain.outbound import (
    NON_SECRET_HEADERS_SCHEMA_VERSION,
    PREPARED_BODY_SCHEMA_VERSION,
    REQUEST_ENVELOPE_SCHEMA_VERSION,
    NonSecretHeader,
    PreparedOutbound,
    validate_prepared_outbound_against_plan,
)
from snapquiz.domain.plan import (
    EXECUTION_PLAN_SCHEMA_VERSION,
    CanonicalQueryPolicy,
    ComputeLocation,
    CredentialInjectionSlot,
    ExecutionPlan,
    ExecutionPlanNetworkOperation,
    ExecutionPlanStage,
    NetworkOperationPurpose,
    NetworkScope,
    OutboundDataKind,
    QueryPolicyKind,
    RequiredConsentScope,
    validate_endpoint_for_network_scope,
    validate_phase1_remote_direct_plan,
)
from snapquiz.domain.policy import (
    ContractMarker,
    PolicySnapshot,
    PolicyValue,
    validate_policy_value_at,
)
from snapquiz.domain.solve import (
    ConfidenceKind,
    PipelineKind,
    SolveProvenance,
    SolveResult,
    SolveStatus,
    StageRole,
    StageProvenance,
    UsageSummary,
)

__all__ = [
    "CANONICAL_SERIALIZER_VERSION",
    "ANSWER_CANDIDATE_SCHEMA_VERSION",
    "AnswerCandidateResult",
    "CaptureArtifact",
    "CaptureConstraints",
    "CaptureRect",
    "CaptureScope",
    "CaptureScopeKind",
    "CapabilityRole",
    "ConfidenceKind",
    "CoordinateSpace",
    "CanonicalQueryPolicy",
    "ComputeLocation",
    "ContractMarker",
    "CredentialBindingMetadata",
    "CredentialInjectionSlot",
    "CredentialValueScheme",
    "Digest256",
    "EXECUTION_PLAN_SCHEMA_VERSION",
    "ExecutionPlan",
    "ExecutionPlanNetworkOperation",
    "ExecutionPlanStage",
    "EndpointOperationTemplate",
    "EndpointPolicySnapshot",
    "ImageInputKind",
    "InputModality",
    "MAX_USER_HINT_CHARS",
    "MAX_PROVIDER_RESPONSE_BYTES",
    "ModelCapabilitiesSnapshot",
    "NON_SECRET_HEADERS_SCHEMA_VERSION",
    "NetworkOperationPurpose",
    "NetworkScope",
    "NonSecretHeader",
    "OutboundDataKind",
    "OutputTokenLimit",
    "NormalizedRefusal",
    "PipelineKind",
    "PipelineProfileSnapshot",
    "PREPARED_BODY_SCHEMA_VERSION",
    "PolicySnapshot",
    "PolicyValue",
    "PreparedOutbound",
    "ProviderApplicationState",
    "ProviderProfileSnapshot",
    "QueryPolicyKind",
    "REQUEST_ENVELOPE_SCHEMA_VERSION",
    "RequiredConsentScope",
    "RedirectPolicy",
    "SOLVE_INTENT_SCHEMA_VERSION",
    "SOLVE_INTENT_DIGEST_SCHEMA_VERSION",
    "SolveIntent",
    "SolveProvenance",
    "SolveResult",
    "SolveStatus",
    "StageRole",
    "StageProvenance",
    "StageBindingSnapshot",
    "StructuredOutputKind",
    "TRANSPORT_RESPONSE_SCHEMA_VERSION",
    "TransportResponse",
    "UsageSummary",
    "canonical_json_bytes",
    "digest256",
    "validate_capture_artifact",
    "validate_endpoint_for_network_scope",
    "validate_phase1_remote_direct_plan",
    "validate_policy_value_at",
    "validate_prepared_outbound_against_plan",
]
